// --- EVENT CATEGORY DEFINITIONS ---
// Each category is a named group of events. Users can toggle categories on/off
// via the settings panel. Multiple categories can be active simultaneously.

const EVENT_CATEGORIES = [
    {
        id: 'key_events',
        name: 'Key events',
        desc: 'Major milestones in the history of the universe, Earth, and civilisation',
        events: [
            { ya: 13.8e9, name: "Big Bang", time: "13.8 bya", desc: "Origin of space, time and matter", type: "milestone" },
            { ya: 13.6e9, name: "First stars", time: "13.6 bya", desc: "Hydrogen ignites across the universe", type: "epoch" },
            { ya: 9e9, name: "Milky Way forms", time: "9 bya", desc: "Our galaxy coalesces from gas", type: "epoch" },
            { ya: 4.6e9, name: "Earth forms", time: "4.6 bya", desc: "Solar system dust gathers into a planet", type: "milestone" },
            { ya: 4.5e9, name: "Moon forms", time: "4.5 bya", desc: "Giant impact sends debris into orbit", type: "epoch" },
            { ya: 3.8e9, name: "First life", time: "3.8 bya", desc: "Single-celled organisms in the oceans", type: "milestone" },
            { ya: 2.4e9, name: "Great Oxygenation", time: "2.4 bya", desc: "Photosynthesis transforms the atmosphere", type: "milestone" },
            { ya: 2e9, name: "Eukaryotes", time: "2 bya", desc: "Cells with a nucleus appear", type: "epoch" },
            { ya: 700e6, name: "Multicellular life", time: "700 mya", desc: "Complex organisms emerge", type: "epoch" },
            { ya: 540e6, name: "Cambrian explosion", time: "540 mya", desc: "Rapid diversification of animal life", type: "milestone" },
            { ya: 375e6, name: "Life onto land", time: "375 mya", desc: "Tetrapods crawl from water to shore", type: "epoch" },
            { ya: 230e6, end_ya: 66e6, name: "Dinosaurs", time: "230–66 mya", desc: "Reign of the dinosaurs begins", type: "epoch", color: "#ffff00" },
            { ya: 230e6, end_ya: 228e6, visibleFrom: 230e6, name: "Earliest Dinosaurs", time: "230–225 mya", desc: "Eoraptor and Herrerasaurus", type: "epoch", color: "#ff9000", offset: 1 },
            { ya: 152e6, end_ya: 149e6, visibleFrom: 230e6, name: "Diplodocus", time: "152–149 mya", desc: "", type: "epoch", color: "#9305ff", offset: 2 },
            { ya: 155e6, end_ya: 145e6, visibleFrom: 230e6, name: "Stegosaurus", time: "155–145 mya", desc: "", type: "epoch", color: "#ff9000", offset: 1 },
            { ya: 69e6, end_ya: 66e6, visibleFrom: 230e6, name: "Tyrannosaurus Rex", time: "69–66 mya", desc: "", type: "epoch", color: "#aa0000", offset: 1 },
            { ya: 68e6, end_ya: 66e6, visibleFrom: 230e6, name: "Triceratops", time: "68–66 mya", desc: "", type: "epoch", color: "#ff9000", offset: 2 },
            { ya: 66e6, name: "Mass extinction", time: "66 mya", desc: "Asteroid ends the dinosaur era", type: "milestone" },
            { ya: 40e6, name: "First monkeys", time: "40 mya", desc: "Primates diverge into Simians and Tarsiers", type: "epoch", color: "#00ff90" },
            { ya: 25e6, name: "First apes", time: "25 mya", desc: "Primates diverge into Old World monkeys and apes", type: "epoch" },
            { ya: 6e6, name: "Hominin split", time: "6 mya", desc: "Human and chimp lineages diverge", type: "epoch" },
            { ya: 1.8e6, end_ya: 108e3, name: "Homo erectus", time: "1.8 million–108,000 ya", desc: "", type: "epoch", color: "#00ff90" },
            { ya: 400e3, end_ya: 40e3, name: "Neanderthals", time: "400,000–40,000 ya", desc: "", type: "epoch", color: "#f15feaff", offset: 1 },
            { ya: 300e3, name: "Homo sapiens", time: "300,000 ya", desc: "Modern humans evolve in Africa", type: "milestone", color: "#00ffaaff" },
            { ya: 70e3, name: "Out of Africa", time: "70,000 ya", desc: "Humans migrate across the globe", type: "milestone", color: "#00ffaaff" },
            { ya: 12e3, name: "Agriculture", time: "12,000 ya", desc: "Farming replaces hunter-gathering", type: "milestone", color: "#00ffaaff" },
            { cal_year: -12e3, end_cal_year: -3e3, name: "Stone Age", time: "12,000–3,000 BCE", desc: "Stone Age", type: "epoch", color: "#999999" },
            { cal_year: -3e3, end_cal_year: -1.2e3, name: "Bronze Age", time: "3,000–1,200 BCE", desc: "Bronze Age", type: "epoch", color: "#ffbb00" },
            { cal_year: -1.2e3, end_cal_year: -500, name: "Iron Age", time: "1,200–500 BCE", desc: "Iron Age", type: "epoch" },
            { ya: 5000, name: "Writing", time: "5,000 ya", desc: "Sumerian cuneiform; recorded history begins", type: "milestone" },
            { ya: 5000, name: "Stonehenge", time: "5,000 ya", desc: "Stonehenge", type: "milestone" },
            { ya: 4500, name: "Great Pyramid of Giza", time: "4,500 ya", desc: "Great Pyramid of Giza", type: "milestone" },
            { cal_year: -800, end_cal_year: -146, name: "Ancient Greece", time: "800–146 BCE", desc: "Philosophy, democracy, and art", type: "milestone", color: "#00ff00", offset: 1 },
            { cal_year: 27, end_cal_year: 476, name: "Roman Empire", time: "27 - 476 CE", desc: "Conquest and engineering", type: "milestone", color: "#ff0000", offset: 1 },
            { cal_year: 1440, name: "Printing press", time: "1440 CE", desc: "Gutenberg democratises knowledge", type: "milestone" },
            { cal_year: 1687, name: "Newton's Principia", time: "1687 CE", desc: "Laws of motion; modern science begins", type: "epoch" },
            { cal_year: 1760, end_cal_year: 1840, name: "Industrial revolution", time: "1760s CE", desc: "Steam power transforms civilisation", type: "milestone" },
            { cal_year: 1850, name: "Germ theory", time: "~1850 CE", desc: "Disease explained; medicine transformed", type: "epoch" },
            { cal_year: 1903, name: "Powered flight", time: "1903 CE", desc: "Wright brothers' first flight", type: "milestone" },
            { cal_year: 1914, end_cal_year: 1918, name: "World War I", time: "1914–18", desc: "Major global conflict", type: "milestone" },
            { cal_year: 1939, end_cal_year: 1945, name: "World War II", time: "1939–45", desc: "Major global conflict", type: "milestone" },
            { cal_year: 1945, name: "Nuclear age", time: "1945 CE", desc: "Atomic bomb; the Cold War begins", type: "epoch" },
            { cal_year: 1969, name: "Moon landing", time: "1969 CE", desc: "Humans walk on another world", type: "milestone" },
            { cal_year: 1991, name: "World Wide Web", time: "1991 CE", desc: "Berners-Lee connects global knowledge", type: "milestone" },
            { cal_year: 2007, name: "Smartphones", time: "2007 CE", desc: "The internet fits in your pocket", type: "epoch" },
            { cal_year: 2020, name: "COVID-19", time: "2020 CE", desc: "Global pandemic halts modern life", type: "milestone" },
            { cal_year: 2022, name: "AI goes mainstream", time: "2022–23 CE", desc: "Large language models reshape culture", type: "milestone" },
        ]
    },
    {
        id: 'famous_scientists',
        name: 'Famous scientists',
        desc: 'Lifespans and key contributions of notable scientists',
        events: [
            { cal_year: -460, end_cal_year: -370, name: "Hippocrates", time: "460–370 BCE", desc: "Father of medicine; Hippocratic Oath", type: "epoch", color: "#4ecdc4" },
            { cal_year: -384, end_cal_year: -322, name: "Aristotle", time: "384–322 BCE", desc: "Greek philosopher; foundations of biology, logic, and physics", type: "epoch", color: "#4ecdc4" },
            { cal_year: -300, end_cal_year: -200, name: "Euclid", time: "300–200 BCE", desc: "Father of geometry; Elements", type: "epoch", color: "#4ecdc4" },
            { cal_year: -287, end_cal_year: -212, name: "Archimedes", time: "287–212 BCE", desc: "Buoyancy, levers, and early calculus concepts", type: "epoch", color: "#4ecdc4" },
            { cal_year: -276, end_cal_year: -195, name: "Eratosthenes", time: "276–195 BCE", desc: "Calculated Earth's circumference with remarkable accuracy", type: "epoch", color: "#4ecdc4" },
            { cal_year: 100, end_cal_year: 170, name: "Ptolemy", time: "100–170 CE", desc: "Geocentric model; astronomy and geography", type: "epoch", color: "#4ecdc4" },
            { cal_year: 450, end_cal_year: 525, name: "Aryabhata", time: "450–525 CE", desc: "Indian mathematician and astronomer; zero, pi, and trigonometry", type: "epoch", color: "#4ecdc4" },
            { cal_year: 780, end_cal_year: 850, name: "Al-Khwarizmi", time: "780–850 CE", desc: "Father of algebra and algorithms", type: "epoch", color: "#4ecdc4" },
            { cal_year: 965, end_cal_year: 1040, name: "Ibn al-Haytham", time: "965–1040", desc: "Father of optics; scientific method", type: "epoch", color: "#4ecdc4" },
            { cal_year: 973, end_cal_year: 1048, name: "Al-Biruni", time: "973–1048", desc: "Polymath; astronomy, mathematics, and history", type: "epoch", color: "#4ecdc4" },
            { cal_year: 980, end_cal_year: 1037, name: "Ibn Sina / Avicenna", time: "980–1037", desc: "Persian polymath; medicine and philosophy", type: "epoch", color: "#4ecdc4" },
            { cal_year: 1214, end_cal_year: 1292, name: "Roger Bacon", time: "1214–1292", desc: "English philosopher; experimental science pioneer", type: "epoch", color: "#4ecdc4" },
            { cal_year: 1473, end_cal_year: 1543, name: "Copernicus", time: "1473–1543", desc: "Proposed the heliocentric model of the solar system", type: "epoch", color: "#4ecdc4" },
            { cal_year: 1564, end_cal_year: 1642, name: "Galileo Galilei", time: "1564–1642", desc: "Father of observational astronomy and modern physics", type: "epoch", color: "#4ecdc4" },
            { cal_year: 1643, end_cal_year: 1727, name: "Isaac Newton", time: "1643–1727", desc: "Laws of motion, gravity, and calculus", type: "epoch", color: "#4ecdc4" },
            { cal_year: 1706, end_cal_year: 1790, name: "Benjamin Franklin", time: "1706–1790", desc: "Electricity experiments; lightning rod inventor", type: "epoch", color: "#4ecdc4" },
            { cal_year: 1791, end_cal_year: 1867, name: "Michael Faraday", time: "1791–1867", desc: "Electromagnetic induction; electric motor foundations", type: "epoch", color: "#4ecdc4" },
            { cal_year: 1809, end_cal_year: 1882, name: "Charles Darwin", time: "1809–1882", desc: "Theory of evolution by natural selection", type: "epoch", color: "#4ecdc4" },
            { cal_year: 1822, end_cal_year: 1895, name: "Louis Pasteur", time: "1822–1895", desc: "Germ theory, pasteurisation, and vaccines", type: "epoch", color: "#4ecdc4" },
            { cal_year: 1831, end_cal_year: 1879, name: "James Clerk Maxwell", time: "1831–1879", desc: "Unified electricity, magnetism, and light", type: "epoch", color: "#4ecdc4" },
            { cal_year: 1856, end_cal_year: 1943, name: "Nikola Tesla", time: "1856–1943", desc: "Alternating current, radio, and wireless power", type: "epoch", color: "#4ecdc4" },
            { cal_year: 1867, end_cal_year: 1934, name: "Marie Curie", time: "1867–1934", desc: "Pioneered radioactivity research; two Nobel Prizes", type: "epoch", color: "#4ecdc4" },
            { cal_year: 1879, end_cal_year: 1955, name: "Albert Einstein", time: "1879–1955", desc: "Relativity, E=mc², and the photoelectric effect", type: "epoch", color: "#4ecdc4" },
            { cal_year: 1885, end_cal_year: 1962, name: "Niels Bohr", time: "1885–1962", desc: "Atomic model and quantum mechanics pioneer", type: "epoch", color: "#4ecdc4" },
            { cal_year: 1901, end_cal_year: 1954, name: "Enrico Fermi", time: "1901–1954", desc: "Nuclear reactor and quantum theory contributions", type: "epoch", color: "#4ecdc4" },
            { cal_year: 1912, end_cal_year: 1954, name: "Alan Turing", time: "1912–1954", desc: "Father of computer science and artificial intelligence", type: "epoch", color: "#4ecdc4" },
            { cal_year: 1918, end_cal_year: 1988, name: "Richard Feynman", time: "1918–1988", desc: "Quantum electrodynamics; iconic science communicator", type: "epoch", color: "#4ecdc4" },
            { cal_year: 1920, end_cal_year: 1958, name: "Rosalind Franklin", time: "1920–1958", desc: "X-ray crystallography of DNA structure", type: "epoch", color: "#4ecdc4" },
            { cal_year: 1928, end_cal_year: 2004, name: "James Watson", time: "1928–2004", desc: "Co-discoverer of DNA structure", type: "epoch", color: "#4ecdc4" },
            { cal_year: 1940, end_cal_year: 2026, name: "Kip Thorne", time: "1940–", desc: "Gravitational wave physics and black holes", type: "epoch", color: "#4ecdc4" },
            { cal_year: 1942, end_cal_year: 2018, name: "Stephen Hawking", time: "1942–2018", desc: "Black holes, cosmology, and A Brief History of Time", type: "epoch", color: "#4ecdc4" },
            { cal_year: 1964, end_cal_year: 2026, name: "Jennifer Doudna", time: "1964–", desc: "Co-discoverer of CRISPR gene editing", type: "epoch", color: "#4ecdc4" },
            { cal_year: 1976, end_cal_year: 2026, name: "Demis Hassabis", time: "1976–", desc: "Co-founder of DeepMind; AI research", type: "epoch", color: "#4ecdc4" },
        ]
    },
    {
        id: 'communication_tech',
        name: 'Communication technology',
        desc: 'Key inventions in how humans share information',
        events: [
            { ya: 40000, name: "Cave paintings", time: "40,000 ya", desc: "Earliest known visual communication", type: "milestone", color: "#ff6b6b" },
            { ya: 5000, name: "Cuneiform writing", time: "~3,000 BCE", desc: "First writing system in Mesopotamia", type: "milestone", color: "#ff6b6b" },
            { ya: 3200, name: "Phoenician alphabet", time: "~1,200 BCE", desc: "First widely-used phonetic alphabet", type: "milestone", color: "#ff6b6b" },
            { cal_year: 105, name: "Paper (China)", time: "105 CE", desc: "Cai Lun standardises papermaking", type: "milestone", color: "#ff6b6b" },
            { cal_year: 1440, name: "Printing press (Gutenberg)", time: "1440 CE", desc: "Movable type revolutionises information spread", type: "milestone", color: "#ff6b6b" },
            { cal_year: 1826, name: "Photographic camera", time: "1826 CE", desc: "First permanent photograph", type: "milestone", color: "#ff6b6b" },
            { cal_year: 1837, name: "Telegraph", time: "1837 CE", desc: "Morse code enables instant long-distance messaging", type: "milestone", color: "#ff6b6b" },
            { cal_year: 1876, name: "Telephone", time: "1876 CE", desc: "Bell patents voice transmission over wire", type: "milestone", color: "#ff6b6b" },
            { cal_year: 1895, name: "Radio", time: "1895 CE", desc: "Marconi demonstrates wireless telegraphy", type: "milestone", color: "#ff6b6b" },
            { cal_year: 1888, name: "Moving image camera", time: "1888 CE", desc: "First moving image camera", type: "milestone", color: "#ff6b6b" },
            { cal_year: 1895, name: "Cinema", time: "1895 CE", desc: "First public film screening", type: "milestone", color: "#ff6b6b" },
            { cal_year: 1927, name: "Television", time: "1927 CE", desc: "Farnsworth demonstrates electronic TV", type: "milestone", color: "#ff6b6b" },
            { cal_year: 1962, name: "Telstar satellite", time: "1962 CE", desc: "First active communications satellite", type: "milestone", color: "#ff6b6b" },
            { cal_year: 1969, name: "ARPANET", time: "1969 CE", desc: "Precursor to the internet goes live", type: "milestone", color: "#ff6b6b" },
            { cal_year: 1971, name: "Email", time: "1971 CE", desc: "First networked email sent by Ray Tomlinson", type: "milestone", color: "#ff6b6b" },
            { cal_year: 1983, name: "Mobile phone", time: "1983 CE", desc: "Motorola DynaTAC: first commercial mobile phone", type: "milestone", color: "#ff6b6b" },
            { cal_year: 1991, name: "World Wide Web (public)", time: "1991 CE", desc: "Berners-Lee opens the web to the public", type: "milestone", color: "#ff6b6b" },
            { cal_year: 1992, name: "SMS text messaging", time: "1992 CE", desc: "First text message sent over GSM", type: "milestone", color: "#ff6b6b" },
            { cal_year: 2004, name: "Facebook", time: "2004 CE", desc: "Social networking goes mainstream", type: "milestone", color: "#ff6b6b" },
            { cal_year: 2007, name: "iPhone", time: "2007 CE", desc: "Touchscreen smartphone redefines communication", type: "milestone", color: "#ff6b6b" },
            { cal_year: 2010, name: "Instagram", time: "2010 CE", desc: "Visual social media takes off", type: "milestone", color: "#ff6b6b" },
            { cal_year: 2022, name: "ChatGPT", time: "2022 CE", desc: "Conversational AI reaches the mainstream", type: "milestone", color: "#ff6b6b" },
        ]
    }
];